### ISSUE TITLE
elastic_transform在使用中变形不明显

### ISSUE THREAD

**Issue by SLKaMiHi** [TimothyZero/MedVision#1]
您好：
我正在使用您提供的代码进行数据增强。您的代码非常全面。但在使用CudaRandomElasticDeformation(CudaAugBase)方法时，每次确实产生了不同的seg，但原图像变化并不明显。如图所示。我想知道怎样才能产生更明显的变形。

![第二次seg](https://user-images.githubusercontent.com/73085198/144703023-fe0d63b5-520e-4b9f-9a6a-77eb25c9e456.png)
![第二次变化结果](https://user-images.githubusercontent.com/73085198/144703025-186745cc-042c-4704-8a50-5892bf28d9fc.png)
![第一次seg](https://user-images.githubusercontent.com/73085198/144703026-3175a9b5-a914-4309-9a47-fb118f883a54.png)
![第一次变化结果](https://user-images.githubusercontent.com/73085198/144703027-fdf0dd48-290a-45cd-9ec7-a98425dcece3.png)
十分感谢！

**Comment by TimothyZero** [comment]
你可以修改num_control_points（越少变形越明显，不建议低于5）或者max_displacement（越大变形越明显，不得超过1）

**Comment by SLKaMiHi** [comment]
> 你可以修改num_control_points（越少变形越明显，不建议低于5）或者max_displacement（越大变形越明显，不得超过1）

按照您的建议我进行了修改，图像的标签确实产生了大的变形，但是我发现，图像并没有产生相应的变形，只是在标签上产生了变形。如图所示：
![变换的图像](https://user-images.githubusercontent.com/73085198/144737863-8c270b13-6d55-4db4-9c29-54e070b438b5.png)
原图像中图像和标签是可以很好的重合的。如下图：
![原图像](https://user-images.githubusercontent.com/73085198/144737881-e2ddfe40-b751-4144-a234-50e3d01f6689.png)
.
此外，我在将方法应用到我自己的数据集的时候产生了如下结果，不知道是为什么，希望您能帮我解答一下。
![自己的数据集](https://user-images.githubusercontent.com/73085198/144737923-0a6481ba-2d53-48d2-855f-900ec8a050bb.png)
非常感谢！

**Comment by TimothyZero** [comment]
非常抱歉，我在版本升级时忘了修改test脚本示例，你需要指定
result = {
            'img_dim':     2,
            'img_spacing': (1.0, 1.0),
            'filename':    img_filename,
            'img':         img,
            'img_fields':  ['img'],
            'gt_det':      det,
            'det_fields':  ['gt_det'],
            'gt_seg':      seg,
            'seg_fields':  ['gt_seg']
        }
中的'img_fields'或det_fields或seg_fields

**Comment by TimothyZero** [comment]
> 此外，我在将方法应用到我自己的数据集的时候产生了如下结果，不知道是为什么，希望您能帮我解答一下。
关于这个你需要注意的是我使用了均值为-400，标准差为700的归一化操作，具体参见`test.load_utils.load_3d_image_with_seg`

**Comment by SLKaMiHi** [comment]
> > 此外，我在将方法应用到我自己的数据集的时候产生了如下结果，不知道是为什么，希望您能帮我解答一下。
> 
> 关于这个你需要注意的是我使用了均值为-400，标准差为700的归一化操作，具体参见`test.load_utils.load_3d_image_with_seg`

根据您的建议我已经得到了正确的结果。非常感谢！
