### ISSUE TITLE
RoIAlign3DFunction中rois的格式是什么？

### ISSUE THREAD

**Issue by windygoo** [TimothyZero/MedVision#2]

**Comment by windygoo** [comment]
为什么star这么少，明明很有用的。

**Comment by TimothyZero** [comment]
哈哈哈，怎么样搞定了吗，我才看到

**Comment by TimothyZero** [comment]
> 为什么star这么少，明明很有用的。

感谢认可，可能是医学影像大家做的少，而且更专注分割吧，这个是我为3D图像检测做的

**Comment by windygoo** [comment]
> 哈哈哈，怎么样搞定了吗，我才看到

嗯嗯，差不多搞定了。想再确认下xyz分别是在d，h，w维度上嘛。能不能加一下您的qq交流一下？

**Comment by TimothyZero** [comment]
微信吧，thyzyfx

> > 哈哈哈，怎么样搞定了吗，我才看到
> 
> 嗯嗯，差不多搞定了。想再确认下xyz分别是在d，h，w维度上嘛。能不能加一下您的qq交流一下？

微信吧，thyzyfx
